/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package views.Muestras;

import Models.Muestras.ModelDetalleResultado;
import java.awt.Dimension;
import java.awt.Toolkit;

/**
 *
 * @author alijmg
 */
public class DetallesResultados extends javax.swing.JInternalFrame {

    int idCita = 0;
    Object[] objeto;
    ModelDetalleResultado detalleresultado = new ModelDetalleResultado();
    public DetallesResultados() {
        initComponents();
        Dimension pantalla = Toolkit.getDefaultToolkit().getScreenSize();
        Dimension ventana = this.getSize();
        this.setLocation((pantalla.width - ventana.width) / 2, ((pantalla.height - ventana.height) / 2) - 40);
    }
    
        public DetallesResultados(int idCita) {
        initComponents();
        this.idCita = idCita;
        this.objeto = detalleresultado.readHeader(idCita);
        this.lbidcita.setText("N°: "+this.objeto[0]);
        this.lbfecha.setText("Fecha emision: "+this.objeto[1].toString());
        this.txtnombrep.setText(this.objeto[2].toString());
        this.txtsexop.setText(this.objeto[3].toString());
        this.txtfechap.setText(this.objeto[4].toString());
        this.txtcedula.setText(this.objeto[5].toString());
        this.txtcorreo.setText(this.objeto[6].toString());
        this.txtdireccionp.setText(this.objeto[7].toString());
        this.txttelefonop.setText(this.objeto[8].toString());
        this.txtnombree.setText(this.objeto[9].toString());
        this.txtcorreoe.setText(this.objeto[10].toString());
        this.txttelefonoe.setText(this.objeto[11].toString());
        this.txtdireccione.setText(this.objeto[12].toString());
        this.tableResultado.setModel(this.detalleresultado.read(idCita));
        Dimension pantalla = Toolkit.getDefaultToolkit().getScreenSize();
        Dimension ventana = this.getSize();
        this.setLocation((pantalla.width - ventana.width) / 2, ((pantalla.height - ventana.height) / 2) - 40);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tableResultado = new javax.swing.JTable();
        jPanel2 = new javax.swing.JPanel();
        lbresultados = new javax.swing.JLabel();
        lbidcita = new javax.swing.JLabel();
        lbfecha = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        lbnombrepaciente = new javax.swing.JLabel();
        lbsexoPaciente = new javax.swing.JLabel();
        lbfechanacimiento = new javax.swing.JLabel();
        lbcedula = new javax.swing.JLabel();
        lbcorreo = new javax.swing.JLabel();
        lbdireccion = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        txtnombrep = new javax.swing.JTextField();
        txtsexop = new javax.swing.JTextField();
        txtfechap = new javax.swing.JTextField();
        txtcedula = new javax.swing.JTextField();
        txtcorreo = new javax.swing.JTextField();
        txtdireccionp = new javax.swing.JTextField();
        txttelefonop = new javax.swing.JTextField();
        jPanel4 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        txtnombree = new javax.swing.JTextField();
        txtcorreoe = new javax.swing.JTextField();
        txttelefonoe = new javax.swing.JTextField();
        txtdireccione = new javax.swing.JTextField();

        setClosable(true);
        setTitle("Resultado");

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jScrollPane1.setBackground(new java.awt.Color(255, 255, 255));
        jScrollPane1.setOpaque(false);

        tableResultado.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        tableResultado.setEnabled(false);
        tableResultado.setGridColor(new java.awt.Color(255, 255, 255));
        tableResultado.setInheritsPopupMenu(true);
        tableResultado.setOpaque(false);
        tableResultado.setShowHorizontalLines(false);
        tableResultado.setShowVerticalLines(false);
        tableResultado.getTableHeader().setResizingAllowed(false);
        jScrollPane1.setViewportView(tableResultado);
        tableResultado.getAccessibleContext().setAccessibleName("");

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));

        lbresultados.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        lbresultados.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbresultados.setText("Resultados Clinicos");

        lbidcita.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        lbidcita.setForeground(new java.awt.Color(255, 0, 0));
        lbidcita.setText("N°:");

        lbfecha.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        lbfecha.setText("Fecha emision:");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbfecha, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lbidcita, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lbresultados, javax.swing.GroupLayout.PREFERRED_SIZE, 700, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbresultados, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(lbidcita)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lbfecha)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));

        lbnombrepaciente.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lbnombrepaciente.setText("Nombre paciente: ");

        lbsexoPaciente.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lbsexoPaciente.setText("Sexo paciente: ");

        lbfechanacimiento.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lbfechanacimiento.setText("Fecha nacimiento: ");

        lbcedula.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lbcedula.setText("Cedula:");

        lbcorreo.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lbcorreo.setText("Correo:");

        lbdireccion.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lbdireccion.setText("Direccion:");

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel7.setText("Telefono: ");

        txtnombrep.setEditable(false);
        txtnombrep.setBackground(new java.awt.Color(255, 255, 255));
        txtnombrep.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtnombrep.setToolTipText("");
        txtnombrep.setBorder(null);
        txtnombrep.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtnombrepActionPerformed(evt);
            }
        });

        txtsexop.setEditable(false);
        txtsexop.setBackground(new java.awt.Color(255, 255, 255));
        txtsexop.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtsexop.setToolTipText("");
        txtsexop.setBorder(null);
        txtsexop.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtsexopActionPerformed(evt);
            }
        });

        txtfechap.setEditable(false);
        txtfechap.setBackground(new java.awt.Color(255, 255, 255));
        txtfechap.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtfechap.setToolTipText("");
        txtfechap.setBorder(null);
        txtfechap.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtfechapActionPerformed(evt);
            }
        });

        txtcedula.setEditable(false);
        txtcedula.setBackground(new java.awt.Color(255, 255, 255));
        txtcedula.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtcedula.setToolTipText("");
        txtcedula.setBorder(null);
        txtcedula.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtcedulaActionPerformed(evt);
            }
        });

        txtcorreo.setEditable(false);
        txtcorreo.setBackground(new java.awt.Color(255, 255, 255));
        txtcorreo.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtcorreo.setToolTipText("");
        txtcorreo.setBorder(null);
        txtcorreo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtcorreoActionPerformed(evt);
            }
        });

        txtdireccionp.setEditable(false);
        txtdireccionp.setBackground(new java.awt.Color(255, 255, 255));
        txtdireccionp.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtdireccionp.setToolTipText("");
        txtdireccionp.setBorder(null);
        txtdireccionp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtdireccionpActionPerformed(evt);
            }
        });

        txttelefonop.setEditable(false);
        txttelefonop.setBackground(new java.awt.Color(255, 255, 255));
        txttelefonop.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txttelefonop.setToolTipText("");
        txttelefonop.setBorder(null);
        txttelefonop.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txttelefonopActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(lbnombrepaciente)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txtnombrep, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lbfechanacimiento)
                                    .addComponent(lbsexoPaciente))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(txtsexop, javax.swing.GroupLayout.DEFAULT_SIZE, 161, Short.MAX_VALUE)
                                    .addComponent(txtfechap))))
                        .addGap(35, 35, 35)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(lbcedula)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(txtcedula, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(lbcorreo)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(txtcorreo, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(jLabel7)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(txttelefonop, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(321, 321, 321)
                        .addComponent(lbdireccion)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 31, Short.MAX_VALUE)
                        .addComponent(txtdireccionp, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbnombrepaciente)
                    .addComponent(lbcedula)
                    .addComponent(txtnombrep, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtcedula, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbsexoPaciente)
                    .addComponent(lbcorreo)
                    .addComponent(txtsexop, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtcorreo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7)
                            .addComponent(txttelefonop, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lbfechanacimiento)
                            .addComponent(txtfechap, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbdireccion)
                    .addComponent(txtdireccionp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel8.setText("nombre Empleado:");

        jLabel9.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel9.setText("Correo Empleado:");

        jLabel10.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel10.setText("Telefono Empleado:");

        jLabel11.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel11.setText("Direccion Empleado:");

        txtnombree.setEditable(false);
        txtnombree.setBackground(new java.awt.Color(255, 255, 255));
        txtnombree.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtnombree.setToolTipText("");
        txtnombree.setBorder(null);
        txtnombree.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtnombreeActionPerformed(evt);
            }
        });

        txtcorreoe.setEditable(false);
        txtcorreoe.setBackground(new java.awt.Color(255, 255, 255));
        txtcorreoe.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtcorreoe.setToolTipText("");
        txtcorreoe.setBorder(null);
        txtcorreoe.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtcorreoeActionPerformed(evt);
            }
        });

        txttelefonoe.setEditable(false);
        txttelefonoe.setBackground(new java.awt.Color(255, 255, 255));
        txttelefonoe.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txttelefonoe.setToolTipText("");
        txttelefonoe.setBorder(null);
        txttelefonoe.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txttelefonoeActionPerformed(evt);
            }
        });

        txtdireccione.setEditable(false);
        txtdireccione.setBackground(new java.awt.Color(255, 255, 255));
        txtdireccione.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtdireccione.setToolTipText("");
        txtdireccione.setBorder(null);
        txtdireccione.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtdireccioneActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jLabel11)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtdireccione, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addComponent(jLabel10)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txttelefonoe, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel8)
                                    .addComponent(jLabel9))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtcorreoe, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtnombree, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addContainerGap(61, Short.MAX_VALUE))))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(txtnombree, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(txtcorreoe, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel10, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(txttelefonoe, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(txtdireccione, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 294, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtnombrepActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtnombrepActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtnombrepActionPerformed

    private void txtsexopActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtsexopActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtsexopActionPerformed

    private void txtfechapActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtfechapActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtfechapActionPerformed

    private void txtcedulaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtcedulaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtcedulaActionPerformed

    private void txtcorreoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtcorreoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtcorreoActionPerformed

    private void txtdireccionpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtdireccionpActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtdireccionpActionPerformed

    private void txttelefonopActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txttelefonopActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txttelefonopActionPerformed

    private void txtnombreeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtnombreeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtnombreeActionPerformed

    private void txtcorreoeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtcorreoeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtcorreoeActionPerformed

    private void txttelefonoeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txttelefonoeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txttelefonoeActionPerformed

    private void txtdireccioneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtdireccioneActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtdireccioneActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lbcedula;
    private javax.swing.JLabel lbcorreo;
    private javax.swing.JLabel lbdireccion;
    private javax.swing.JLabel lbfecha;
    private javax.swing.JLabel lbfechanacimiento;
    private javax.swing.JLabel lbidcita;
    private javax.swing.JLabel lbnombrepaciente;
    private javax.swing.JLabel lbresultados;
    private javax.swing.JLabel lbsexoPaciente;
    private javax.swing.JTable tableResultado;
    private javax.swing.JTextField txtcedula;
    private javax.swing.JTextField txtcorreo;
    private javax.swing.JTextField txtcorreoe;
    private javax.swing.JTextField txtdireccione;
    private javax.swing.JTextField txtdireccionp;
    private javax.swing.JTextField txtfechap;
    private javax.swing.JTextField txtnombree;
    private javax.swing.JTextField txtnombrep;
    private javax.swing.JTextField txtsexop;
    private javax.swing.JTextField txttelefonoe;
    private javax.swing.JTextField txttelefonop;
    // End of variables declaration//GEN-END:variables
}
