
package views.Facturas;

import Models.Citas.ModelDetalleCita;
import Models.Facturas.ModelDetalleFacturas;
import views.Muestras.*;
import Models.Muestras.ModelDetalleResultado;
import java.awt.Dimension;
import java.awt.Toolkit;


public class DetallesFacturas extends javax.swing.JInternalFrame {

    int idfactura = 0;
    Object[] objeto;
    ModelDetalleFacturas detallefacturas = new ModelDetalleFacturas(); 
    ModelDetalleCita detalle = new ModelDetalleCita();
    
    public DetallesFacturas() {
        initComponents();
        Dimension pantalla = Toolkit.getDefaultToolkit().getScreenSize();
        Dimension ventana = this.getSize();
        this.setLocation((pantalla.width - ventana.width) / 2, ((pantalla.height - ventana.height) / 2) - 40);
    }
    
        public DetallesFacturas(int idfac) {
        initComponents();
        this.idfactura = idfac;
        this.objeto = detallefacturas.readHeader(idfac);
        this.lbidcita.setText("N°: "+this.objeto[0]);
        this.lbfecha.setText("Fecha emision: "+this.objeto[1].toString());
        this.txtnombrep.setText(this.objeto[2].toString());
        this.txtsexop.setText(this.objeto[3].toString());
        this.txtfechap.setText(this.objeto[4].toString());
        this.txtcedula.setText(this.objeto[5].toString());
        this.txtcorreo.setText(this.objeto[6].toString());
        this.txtdireccionp.setText(this.objeto[7].toString());
        this.txttelefonop.setText(this.objeto[8].toString());
        this.totaltxt.setText(this.objeto[9].toString());
        this.tableResultado.setModel(this.detallefacturas.mostrarInterfaz(idfac));
        Dimension pantalla = Toolkit.getDefaultToolkit().getScreenSize();
        Dimension ventana = this.getSize();
        this.setLocation((pantalla.width - ventana.width) / 2, ((pantalla.height - ventana.height) / 2) - 40);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tableResultado = new javax.swing.JTable();
        jPanel2 = new javax.swing.JPanel();
        lbresultados = new javax.swing.JLabel();
        lbidcita = new javax.swing.JLabel();
        lbfecha = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        lbnombrepaciente = new javax.swing.JLabel();
        lbsexoPaciente = new javax.swing.JLabel();
        lbfechanacimiento = new javax.swing.JLabel();
        lbcedula = new javax.swing.JLabel();
        lbcorreo = new javax.swing.JLabel();
        lbdireccion = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        txtnombrep = new javax.swing.JTextField();
        txtsexop = new javax.swing.JTextField();
        txtfechap = new javax.swing.JTextField();
        txtcedula = new javax.swing.JTextField();
        txtcorreo = new javax.swing.JTextField();
        txtdireccionp = new javax.swing.JTextField();
        txttelefonop = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        totaltxt = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setClosable(true);
        setTitle("Resultado");

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jScrollPane1.setBackground(new java.awt.Color(255, 255, 255));
        jScrollPane1.setOpaque(false);

        tableResultado.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        tableResultado.setEnabled(false);
        tableResultado.setGridColor(new java.awt.Color(255, 255, 255));
        tableResultado.setInheritsPopupMenu(true);
        tableResultado.setOpaque(false);
        tableResultado.setShowHorizontalLines(false);
        tableResultado.setShowVerticalLines(false);
        tableResultado.getTableHeader().setResizingAllowed(false);
        jScrollPane1.setViewportView(tableResultado);
        tableResultado.getAccessibleContext().setAccessibleName("");

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));

        lbresultados.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        lbresultados.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbresultados.setText("Factura");

        lbidcita.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        lbidcita.setForeground(new java.awt.Color(255, 0, 0));
        lbidcita.setText("N°:");

        lbfecha.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        lbfecha.setText("Fecha emision:");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lbfecha, javax.swing.GroupLayout.DEFAULT_SIZE, 165, Short.MAX_VALUE)
                .addGap(241, 241, 241)
                .addComponent(lbresultados, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lbidcita, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(377, 377, 377))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(lbresultados, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(lbidcita))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(35, 35, 35)
                        .addComponent(lbfecha)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));

        lbnombrepaciente.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lbnombrepaciente.setText("Nombre paciente: ");

        lbsexoPaciente.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lbsexoPaciente.setText("Sexo paciente: ");

        lbfechanacimiento.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lbfechanacimiento.setText("Fecha nacimiento: ");

        lbcedula.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lbcedula.setText("Cedula:");

        lbcorreo.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lbcorreo.setText("Correo:");

        lbdireccion.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lbdireccion.setText("Direccion:");

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel7.setText("Telefono: ");

        txtnombrep.setEditable(false);
        txtnombrep.setBackground(new java.awt.Color(255, 255, 255));
        txtnombrep.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtnombrep.setToolTipText("");
        txtnombrep.setBorder(null);
        txtnombrep.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtnombrepActionPerformed(evt);
            }
        });

        txtsexop.setEditable(false);
        txtsexop.setBackground(new java.awt.Color(255, 255, 255));
        txtsexop.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtsexop.setToolTipText("");
        txtsexop.setBorder(null);
        txtsexop.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtsexopActionPerformed(evt);
            }
        });

        txtfechap.setEditable(false);
        txtfechap.setBackground(new java.awt.Color(255, 255, 255));
        txtfechap.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtfechap.setToolTipText("");
        txtfechap.setBorder(null);
        txtfechap.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtfechapActionPerformed(evt);
            }
        });

        txtcedula.setEditable(false);
        txtcedula.setBackground(new java.awt.Color(255, 255, 255));
        txtcedula.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtcedula.setToolTipText("");
        txtcedula.setBorder(null);
        txtcedula.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtcedulaActionPerformed(evt);
            }
        });

        txtcorreo.setEditable(false);
        txtcorreo.setBackground(new java.awt.Color(255, 255, 255));
        txtcorreo.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtcorreo.setToolTipText("");
        txtcorreo.setBorder(null);
        txtcorreo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtcorreoActionPerformed(evt);
            }
        });

        txtdireccionp.setEditable(false);
        txtdireccionp.setBackground(new java.awt.Color(255, 255, 255));
        txtdireccionp.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtdireccionp.setToolTipText("");
        txtdireccionp.setBorder(null);
        txtdireccionp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtdireccionpActionPerformed(evt);
            }
        });

        txttelefonop.setEditable(false);
        txttelefonop.setBackground(new java.awt.Color(255, 255, 255));
        txttelefonop.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txttelefonop.setToolTipText("");
        txttelefonop.setBorder(null);
        txttelefonop.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txttelefonopActionPerformed(evt);
            }
        });

        jLabel11.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel11.setText("Monto total:");

        totaltxt.setEditable(false);
        totaltxt.setBackground(new java.awt.Color(255, 255, 255));
        totaltxt.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        totaltxt.setToolTipText("");
        totaltxt.setBorder(null);
        totaltxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                totaltxtActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel3.setText("$");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(lbnombrepaciente)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtnombrep, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lbfechanacimiento)
                            .addComponent(lbsexoPaciente))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtsexop, javax.swing.GroupLayout.DEFAULT_SIZE, 161, Short.MAX_VALUE)
                            .addComponent(txtfechap)))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(lbdireccion)
                        .addGap(64, 64, 64)
                        .addComponent(txtdireccionp, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(31, 31, 31)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(lbcedula)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(txtcedula, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(lbcorreo)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(txtcorreo, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(jLabel7)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 42, Short.MAX_VALUE)
                                .addComponent(txttelefonop, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addContainerGap())
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel11)
                        .addGap(18, 18, 18)
                        .addComponent(totaltxt, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel3)
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbnombrepaciente)
                    .addComponent(lbcedula)
                    .addComponent(txtnombrep, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtcedula, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbsexoPaciente)
                    .addComponent(lbcorreo)
                    .addComponent(txtsexop, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtcorreo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7)
                            .addComponent(txttelefonop, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lbfechanacimiento)
                            .addComponent(txtfechap, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbdireccion)
                    .addComponent(txtdireccionp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel11)
                    .addComponent(totaltxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 48, Short.MAX_VALUE)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 155, Short.MAX_VALUE)
        );

        jLabel1.setFont(new java.awt.Font("COCOGOOSE ", 2, 12)); // NOI18N
        jLabel1.setText("Tu salud, nuestra prioridad.");

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/publics/img/amlab.png"))); // NOI18N
        jLabel2.setText("jLabel2");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(115, 115, 115)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(38, 38, 38)
                        .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(18, 18, 18))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel1)
                        .addGap(41, 41, 41)))
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 384, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtnombrepActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtnombrepActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtnombrepActionPerformed

    private void txtsexopActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtsexopActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtsexopActionPerformed

    private void txtfechapActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtfechapActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtfechapActionPerformed

    private void txtcedulaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtcedulaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtcedulaActionPerformed

    private void txtcorreoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtcorreoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtcorreoActionPerformed

    private void txtdireccionpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtdireccionpActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtdireccionpActionPerformed

    private void txttelefonopActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txttelefonopActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txttelefonopActionPerformed

    private void totaltxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_totaltxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_totaltxtActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lbcedula;
    private javax.swing.JLabel lbcorreo;
    private javax.swing.JLabel lbdireccion;
    private javax.swing.JLabel lbfecha;
    private javax.swing.JLabel lbfechanacimiento;
    private javax.swing.JLabel lbidcita;
    private javax.swing.JLabel lbnombrepaciente;
    private javax.swing.JLabel lbresultados;
    private javax.swing.JLabel lbsexoPaciente;
    private javax.swing.JTable tableResultado;
    private javax.swing.JTextField totaltxt;
    private javax.swing.JTextField txtcedula;
    private javax.swing.JTextField txtcorreo;
    private javax.swing.JTextField txtdireccionp;
    private javax.swing.JTextField txtfechap;
    private javax.swing.JTextField txtnombrep;
    private javax.swing.JTextField txtsexop;
    private javax.swing.JTextField txttelefonop;
    // End of variables declaration//GEN-END:variables
}
